steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME-$_BRANCH_NAME-backend:$COMMIT_SHA'
      - '--file'
      - blog/Dockerfile
      - blog
    id: Containerize & Test Backend
    waitFor:
      - '-'
    timeout: 500s

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '--build-arg'
      - 'ENVIRONMENT=${_ENVIRONMENT}'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME-$_BRANCH_NAME:$COMMIT_SHA
      - '--file'
      - frontend/frontend.dockerfile
      - frontend
    id: Containerize & Test Frontend
    waitFor:
      - '-'
    timeout: 500s

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME-$_BRANCH_NAME-backend:$COMMIT_SHA'
    id: Push Backend
    waitFor:
      - Containerize & Test Backend
      - Containerize & Test Frontend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME-$_BRANCH_NAME:$COMMIT_SHA
    id: Push Frontend
    waitFor:
      - Containerize & Test Backend
      - Containerize & Test Frontend

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME-$_BRANCH_NAME-backend
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME-$_BRANCH_NAME-backend:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy Backend
    waitFor:
      - Push Backend
    entrypoint: gcloud

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME-$_BRANCH_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME-$_BRANCH_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy Frontend
    waitFor:
      - Push Frontend
    entrypoint: gcloud

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME-$_BRANCH_NAME-backend:$COMMIT_SHA'
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME-$_BRANCH_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _PLATFORM: managed
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _SERVICE_NAME: zenith
  _DEPLOY_REGION: us-central1
  _TRIGGER_ID: c8e3bdfd-dc5f-4a9f-9f0e-cafb8c00e07b
  _BRANCH_NAME: ${BRANCH_NAME}
  _ENVIRONMENT: ${BRANCH_NAME}

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
timeout: 800s

