name: Pull Request to QA on successfull push/pull to dev

on:
  push:
    branches:
      - 'dev'
      - 'dev/**'
      - 'qa/**'

jobs:
  testBackend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      
      - name: Build backend docker image, in which tests will run
        run: docker build -t "zenith/backend-test:latest" --file ./blog/Dockerfile ./blog
  
  testFrontend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Build frontend docker image, in which tests will run
        run: docker build -t "zenith/frontend-test:latest" --file ./frontend/frontend.dockerfile ./frontend

  cleanUp:
    if: always()
    runs-on: ubuntu-latest
    needs: 
      - testBackend
      - testFrontend
    steps:
      - uses: actions/checkout@v3

      - name: Cleans up images
        run: docker image prune --all

  deploy:
    if: github.ref == 'refs/heads/dev'
    needs:
      - testBackend
      - testFrontend
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          
      - name: Fetch remote changes
        run: git fetch -a

      - name: Change working branch to qa
        run: git checkout qa

      - name: Merge dev to qa
        run: git merge dev

      - name: Push changes
        run: git push
  
  notify:
    timeout-minutes: 3
    if: always()
    needs: 
      - deploy
      - cleanUp
    runs-on: ubuntu-latest
    steps:
      - name: Sends report of commit to project slack channel
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C051QF11FB6'
          slack-message: "${{ github.ref_name }} Build Result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

