name: Pull Request to QA on successfull push/pull to dev

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build backend docker image, in which tests will run
        run: docker build -t "zenith/backend-test:latest" --file ./blog/Dockerfile ./blog
        
      - name: Build frontend docker image, in which tests will run
        run: docker build -t "zenith/frontend-test:latest" --file ./frontend/frontend.dockerfile ./frontend
      
      - name: Cleans up images
        if: always()
        run: docker image prune --all
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          
      - name: Fetch remote changes
        run: git fetch -a

      - name: Change working branch to qa
        run: git checkout qa

      - name: marge dev to qa
        run: git merge dev
  
  notify:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Sends report of commit to project slack channel
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
